micronaut:
  application:
    name: notes
---
mongodb:
  cluster:
    maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
    server-selection-timeout: 5s
  uri: mongodb://localhost:27017
  database: notes
  options:
    maxConnectionIdleTime: 5s
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
