micronaut:
  application:
    name: notes
---
micronaut:
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: 661817635087-4jdsbddvft63kgptrs56sp8ieerddgp9.apps.googleusercontent.com
          client-secret: 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
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
---
micronaut:
  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        enabled: true
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
endpoints:
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
---
mongodb:
  cluster:
    maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
    server-selection-timeout: 5s
  uri: mongodb://mongodb:27017
  database: notes
  options:
    maxConnectionIdleTime: 5s
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
